import { ROWS_PER_PAGE } from './arduinoConstants.js';
import { database } from './arduinoCore.js';

export function generatePagination(t,p){if(p.totalPages<=1)return'';return `<div class="pagination" data-table-index="${t}"><button class="pagination-button" data-action="first" ${p.pageNumber===1?'disabled':''}></button><button class="pagination-button" data-action="prev" ${p.pageNumber===1?'disabled':''}></button><div class="pagination-info">Page <input type="number" class="pagination-input" value="${p.pageNumber}" min="1" max="${p.totalPages}" data-table-index="${t}"> / ${p.totalPages}</div><button class="pagination-button" data-action="next" ${p.pageNumber===p.totalPages?'disabled':''}></button><button class="pagination-button" data-action="last" ${p.pageNumber===p.totalPages?'disabled':''}></button></div>`}

export function attachPaginationEvents(r){document.querySelectorAll('.pagination-button').forEach(b=>b.replaceWith(b.cloneNode(!0)));document.querySelectorAll('.pagination-button').forEach(b=>b.addEventListener('click',e=>h(e,r)));document.querySelectorAll('.pagination-input').forEach(i=>{i.addEventListener('change',e=>p(e,r));i.addEventListener('keypress',e=>{if(e.key==='Enter')e.target.dispatchEvent(new Event('change'))})})}

function h(e,r){const b=e.currentTarget,div=b.closest('.pagination');if(!div)return;const ti=parseInt(div.dataset.tableIndex),t=database.tables[ti];if(!t)return;const cp=database.currentPages[ti]||1,tp=Math.ceil(t.data.length/ROWS_PER_PAGE);let np=cp;switch(b.dataset.action){case'first':np=1;break;case'prev':np=Math.max(1,cp-1);break;case'next':np=Math.min(tp,cp+1);break;case'last':np=tp}if(np!==cp){database.currentPages[ti]=np;r();setTimeout(()=>{const tb=document.querySelector(`.table-block[data-table-index="${ti}"] .table-wrapper`);if(tb)tb.scrollTop=0},50)}}

function p(e,r){const i=e.currentTarget,div=i.closest('.pagination');if(!div)return;const ti=parseInt(div.dataset.tableIndex),t=database.tables[ti];if(!t)return;const tp=Math.ceil(t.data.length/ROWS_PER_PAGE),np=parseInt(i.value);if(!isNaN(np)&&np>=1&&np<=tp){database.currentPages[ti]=np;r();setTimeout(()=>{const tb=document.querySelector(`.table-block[data-table-index="${ti}"] .table-wrapper`);if(tb)tb.scrollTop=0},50)}else i.value=database.currentPages[ti]||1}
